# Donne le nom du workflow qui sera visible dans l’onglet Actions de GitHub.
name: Verification de story-droles-de-lettres

# Définit les événements qui déclenchent le workflow. 
on:
  # Le workflow sera déclenché lorsqu’une pull request est ouverte. 
  pull_request:
  # Le workflow sera déclenché lorsqu’un push est effectué sur la branche main.
  push:
    branches: 
      - main

# Donne la liste des jobs à effectuer.
jobs:
  # Crée un job nommé mon-premier-job-de-test.
  mon-premier-job-de-test:
    # Définit le type de machine virtuelle sur laquelle le job sera exécuté.
    runs-on: ubuntu-latest

    # Donne la liste des étapes à effectuer dans le job mon-premier-job-de-test.
    steps:
      - name: Afficher un message
        run: echo "La pipeline Github Actions fonctionne correctement !"  # echo est une commande bash qui affiche un message dans les logs.

      - name: Afficher un second message
        run: echo "Ceci est mon deuxième message dans les logs."

      - name: Afficher un troisième message
        run: echo "Et voici mon troisième message."
  
  verification-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
      
      - name: Vérifier que le fichier HTML existe
        run: test -f index.html
        
      - name: Vérifier que le fichier bidule existe
        run: test -f bidule.html        